packages:
  - name: estimator
    environment:
      DB_NAME: "${DB_NAME}"
      MONGO_URI: "${MONGO_URI}"
      HMAC_KEY_ID: "${HMAC_KEY_ID}"
      HMAC_SECRET_B64: "${HMAC_SECRET_B64}"
      JWT_PUBLIC_KEY_PEM: "${JWT_PUBLIC_KEY_PEM}"
      LOG_LEVEL: "${LOG_LEVEL:info}"
      JWT_ISSUER: "${JWT_ISSUER:efofx-estimate}"
    functions:
      - name: manifest
        runtime: "nodejs:18"
        web: true
        limits: { timeout: 2000, memory: 256 }
      - name: reference_classes-query
        runtime: "nodejs:18"
        web: true
        limits: { timeout: 2500, memory: 256 }
      - name: reference_classes-get
        runtime: "nodejs:18"
        web: true
        limits: { timeout: 2000, memory: 256 }
      - name: adjustments-apply
        runtime: "nodejs:18"
        web: true
        limits: { timeout: 2000, memory: 256 }
